site_name: Risk of Rain 2 Modding Wiki
site_description: 'This wiki contains information and other resources to aid with modding Risk of Rain 2.'
site_author: 'Risk of Rain 2 Modding Community'
docs_dir: docs/
repo_name: 'risk-of-thunder/R2Wiki'
repo_url: 'risk-of-thunder/R2Wiki'
theme:
  name: 'material'
